sudo: required
dist: trusty
language: go
go:
  - 1.5
before_install:
  - pip install --user codecov
install:
  - cd server 
  - go get -d -t ./...
script: 
  - ./go.test.sh
after_success:
  - codecov
